### ISSUE TITLE
Does 'hover' need additional setup to make it work?

### ISSUE THREAD

**Issue by nkakouros** [mads-hartmann/bash-language-server#107]
On the [vs code](https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode) page for this language server's plugin it says:

```
o get documentation for flags on hover (thanks to explainshell), run the explainshell Docker container:

docker run --rm --name bash-explainshell -p 5000:5000 chrismwendt/codeintel-bash-with-explainshell

And add this to your VS Code settings:

    "bashIde.explainshellEndpoint": "http://localhost:5000",
```

I am using neovim. I have 'go to declaration' and some diagnostics working. However, 'hover' does nothing. Should I follow extra steps to set it up or is it incompatible with neovim?

**Comment by skovhus** [comment]
I'm not sure how you forward options in neovim. But you do need to run the docker image as explained and configure the explainshellEndpoin option. 

Please let us know if you figure it out.

**Comment by AmjadHD** [comment]
I'm using it in Sublime Text, it works fine untill I hover over a name (e.g kill), it crashes:
Here I opened a .sh file and hover over a name (kill), this is the log of the [LSP](https://github.com/tomv564/LSP) client:
```
LSP: global configs ['clangd=False', 'typescript-language-server=False', 'jdtls=True', 'bashls=True', 'phpls=False', 'javascript-typescript-langserver=False', 'pyls=True', 'polymer-ide=False', 'rls=True', 'haskell-ide-engine=False', 'reason=False', 'ocaml=False', 'kotlinls=True', 'vscode-css=True', 'cquery=False', 'mspyls=False', 'vscode-json=True', 'eslint=False', 'lsp-tsserver=True', 'vscode-html=True', 'golsp=False', 'julials=False']
LSP: window 2 starting 1 initial views
LSP: window 2 requests bashls for D:\Downloads\Applications\languageserver.sh
LSP: starting in C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\hover-preview
LSP: starting ['bash-language-server.cmd', 'start']
LSP:  --> initialize
LSP: window 2 added session bashls
LSP: <--  window/logMessage
server: Initialized server v. 1.5.6 for file:///C:/Users/Lehdhili/AppData/Roaming/Sublime%20Text%203/Packages/hover-preview
LSP:      {'capabilities': {'textDocumentSync': 1, 'hoverProvider': True, 'completionProvider': {'resolveProvider': True}, 'definitionProvider': True, 'documentSymbolProvider': True, 'referencesProvider': True, 'documentHighlightProvider': True}}
LSP:  --> initialized
LSP:  --> textDocument/didOpen
LSP: <--  textDocument/publishDiagnostics
LSP:      {'uri': 'file:///D:/Downloads/Applications/languageserver.sh', 'diagnostics': []}
LSP:  --> textDocument/hover
LSP: <--  window/logMessage
server: Hovering over 33:7
server: events.js:173
server: throw er; // Unhandled 'error' event
server: ^
server: 
server: Error: spawn bash ENOENT
server: at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
server: at onErrorNT (internal/child_process.js:421:16)
server: at processTicksAndRejections (internal/process/next_tick.js:76:17)
server: Emitted 'error' event at:
server: at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
server: at onErrorNT (internal/child_process.js:421:16)
server: at processTicksAndRejections (internal/process/next_tick.js:76:17)
LSP: LSP stream logger stopped.
LSP: LSP stdout process ended.
```

**Comment by otreblan** [comment]
You need to export the enviroment variable `EXPLAINSHELL_ENDPOINT` to make it work on neovim.
`export EXPLAINSHELL_ENDPOINT="http://localhost:5000"`
Or inside init.vim:
`let $EXPLAINSHELL_ENDPOINT = "http://localhost:5000"`

**Comment by skovhus** [comment]
I'm closing this due to inactivity. Please create a new issue if this is still a problem.
