### ISSUE TITLE
Message header must separate key and value using

### ISSUE THREAD

**Issue by rickywu** [mads-hartmann/bash-language-server#137]
I got error on Windows but works well on WSL:

> C:\Users\Ricky>bash-language-server start
> d:\nodejs\node_modules\bash-language-server\node_modules\vscode-jsonrpc\lib\messageReader.js:57
>                 throw new Error('Message header must separate key and value using :');
>                 ^
> Error: Message header must separate key and value using :
>     at headers.forEach (d:\nodejs\node_modules\bash-language-server\node_modules\vscode-jsonrpc\lib\messageReader.js:57:23)
>     at Array.forEach (<anonymous>)
>     at MessageBuffer.tryReadHeaders (d:\nodejs\node_modules\bash-language-server\node_modules\vscode-jsonrpc\lib\messageReader.js:54:17)
>     at StreamMessageReader.onData (d:\nodejs\node_modules\bash-language-server\node_modules\vscode-jsonrpc\lib\messageReader.js:157:43)
>     at ReadStream.readable.on (d:\nodejs\node_modules\bash-language-server\node_modules\vscode-jsonrpc\lib\messageReader.js:148:18)
>     at ReadStream.emit (events.js:198:13)
>     at addChunk (_stream_readable.js:288:12)
>     at readableAddChunk (_stream_readable.js:269:11)
>     at ReadStream.Readable.push (_stream_readable.js:224:10)
>     at TTY.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```
C:\Users\Ricky>bash-language-server -v
Version is 1.5.6
```

**Comment by rickywu** [comment]
Seems it's bacause of blank input
