### ISSUE TITLE
TypeError: namedDeclarations.push is not a function

### ISSUE THREAD

**Issue by iongion** [mads-hartmann/bash-language-server#146]
I do not know why this shows up whenever I start VSCode:

```
Initialized server v. 1.5.6 for file:///myproject
Analyzing file:///myproject/deploy.sh
Analyzing file:///myproject/node_modules/@babel/polyfill/scripts/build-dist.sh
Analyzing file:///myproject/node_modules/@blueprintjs/core/scripts/upgrade-blueprint-2.0.0-rename.sh
/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/analyser.js:213
                namedDeclarations.push(LSP.SymbolInformation.create(name, this.treeSitterTypeToLSPKind[n.type], TreeSitterUtil.range(n), uri, parentName));
                                  ^

TypeError: namedDeclarations.push is not a function
    at TreeSitterUtil.forEach (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/analyser.js:213:35)
    at forEach (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:6:5)
    at node.children.forEach.n (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:36)
    at Array.forEach (<anonymous>)
    at forEach (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:23)
    at node.children.forEach.n (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:36)
    at Array.forEach (<anonymous>)
    at forEach (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:23)
    at node.children.forEach.n (/home/myuser/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:36)
    at Array.forEach (<anonymous>)
[Info  - 1:13:43 PM] Connection to server got closed. Server will restart

```

Any way to silence it ?

**Comment by skovhus** [comment]
We have just released a new version of `bash-language-server`, can you try that out?

To upgrade run:
```
npm i -g bash-language-server
```

**Comment by iongion** [comment]
It is still an issue with 1.6.0

```
Initialized server v. 1.6.0 for file:///myproject
Analyzing file:///myproject/deploy.sh
Analyzing file:///myproject/node_modules/@babel/polyfill/scripts/build-dist.sh
Analyzing file:///myproject/node_modules/@blueprintjs/core/scripts/upgrade-blueprint-2.0.0-rename.sh
/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readBinary(e){var t=Module.read(e,!0);return t.buffer||(t=new Uint8Array(t)),assert(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.arg

TypeError: namedDeclarations.push is not a function
    at TreeSitterUtil.forEach (catout/analyser.js:210:35)
    at forEach (/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:6:5)
    at node.children.forEach.n (/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:36)
    at Array.forEach (<anonymous>)
    at forEach (/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:23)
    at node.children.forEach.n (/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:36)
    at Array.forEach (<anonymous>)
    at forEach (/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:23)
    at node.children.forEach.n (/myproject/versions/node/v10.16.0/lib/node_modules/bash-language-server/out/util/tree-sitter.js:8:36)
    at Array.forEach (<anonymous>)
[Info  - 11:20:04 AM] Connection to server got closed. Server will restart.
```

This the npm package:

```
cat ~/.nvm/versions/node/v10.16.0/lib/node_modules/bash-language-server/package.json 
{
  "_from": "bash-language-server",
  "_id": "bash-language-server@1.6.0",
  "_inBundle": false,
  "_integrity": "sha512-MFQXEkWasH8s7sPgaLjr+mZkxkVAZYGdg+4/FBs/exIifnpSvr8oM5cH5vnoexPp9MxmopAGHhsmRaURabYzaA==",
  "_location": "/bash-language-server",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "bash-language-server",
    "name": "bash-language-server",
    "escapedName": "bash-language-server",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/bash-language-server/-/bash-language-server-1.6.0.tgz",
  "_shasum": "e27c164b55cdab31f1c8244f660d191910972fc4",
  "_spec": "bash-language-server",
  "_where": "/home/istoica/Workspace/sportshub.keemotion.com",
  "author": {
    "name": "Mads Hartmann"
  },
  "bin": {
    "bash-language-server": "./bin/main.js"
  },
  "bugs": {
    "url": "https://github.com/mads-hartmann/bash-language-server/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "glob": "^7.1.2",
    "request": "^2.83.0",
    "request-promise-native": "^1.0.5",
    "turndown": "^4.0.2",
    "urijs": "^1.19.1",
    "vscode-languageserver": "^4.1.1",
    "web-tree-sitter": "^0.15.9"
  },
  "deprecated": false,
  "description": "A language server for Bash",
  "engines": {
    "node": "*"
  },
  "homepage": "https://github.com/mads-hartmann/bash-language-server#readme",
  "license": "MIT",
  "main": "out/server.js",
  "name": "bash-language-server",
  "publisher": "mads-hartmann",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mads-hartmann/bash-language-server.git"
  },
  "scripts": {
    "compile": "rm -rf out && ../node_modules/.bin/tsc -p ./",
    "compile:watch": "../node_modules/.bin/tsc -w -p ./",
    "prepublishOnly": "yarn run compile"
  },
  "version": "1.6.0"
}
```

**Comment by skovhus** [comment]
Happens for any .sh file? Really puzzled why no one else reports this error... which version of node are you using (node —version)?

**Comment by skovhus** [comment]
@iongion is this still a problem with the latest bash-language-server?

**Comment by iongion** [comment]
@skovhus  No, I did not notice it anymore.

**Comment by slopedog** [comment]
I have this problem with emacs in Ubuntu 18.04 with node 8.10.0 and bls 1.7.0.

```/home/jah/.npm-global/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1
(function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.lengt

TypeError: namedDeclarations.push is not a function
    at TreeSitterUtil.forEach (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/analyser.js:211:35)
    at forEach (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/util/tree-sitter.js:5:5)
    at node.children.forEach.n (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/util/tree-sitter.js:7:36)
    at Array.forEach (<anonymous>)
    at forEach (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/util/tree-sitter.js:7:23)
    at node.children.forEach.n (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/util/tree-sitter.js:7:36)
    at Array.forEach (<anonymous>)
    at forEach (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/util/tree-sitter.js:7:23)
    at node.children.forEach.n (/home/jah/.npm-global/lib/node_modules/bash-language-server/out/util/tree-sitter.js:7:36)
    at Array.forEach (<anonymous>)

Process bash-ls stderr<1> finished

Process bash-ls stderr finished
/home/jah/.npm-global/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1
```

**Comment by penn201500** [comment]
emacs 26.3 ,osx 10.14 , node v10.13.0, bls 1.11.1
I have this same problem
