### ISSUE TITLE
Python may be required for development

### ISSUE THREAD

**Issue by rcjsuen** [mads-hartmann/bash-language-server#2]
Are developers expected to have Python installed? If yes, could this be mentioned in the README.md somewhere?
```
> git clone https://github.com/mads-hartmann/bash-language-server.git
Cloning into 'bash-language-server'...
remote: Counting objects: 125, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 125 (delta 64), reused 94 (delta 39), pack-reused 0
Receiving objects: 100% (125/125), 62.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (64/64), done.

> cd bash-language-server

> npm install
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:8060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> bash-language-server@1.0.0 postinstall bash-language-server
> cd server && npm install && cd ../vscode-client && npm install && cd ..


> tree-sitter@0.9.2 install bash-language-server\server\node_modules\tree-sitter
> node-gyp rebuild


bash-language-server\server\node_modules\tree-sitter>if not defined npm_config_node_gyp (node "npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd bash-language-server\server\node_modules\tree-sitter
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
bash-language-server@1.0.0 bash-language-server\server
+-- glob@7.1.2
| +-- fs.realpath@1.0.0
| +-- inflight@1.0.6
| | `-- wrappy@1.0.2
| +-- inherits@2.0.3
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- once@1.4.0
| `-- path-is-absolute@1.0.1
+-- tree-sitter-bash@0.5.0
| `-- nan@2.9.2
`-- vscode-languageserver@3.5.0
  +-- vscode-languageserver-protocol@3.5.0
  | +-- vscode-jsonrpc@3.5.0
  | `-- vscode-languageserver-types@3.5.0
  `-- vscode-uri@1.0.1

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.9.4
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE

npm ERR! tree-sitter@0.9.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.9.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tree-sitter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tree-sitter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tree-sitter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     bash-language-server\server\npm-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.9.4
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! bash-language-server@1.0.0 postinstall: `cd server && npm install && cd ../vscode-client && npm install && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bash-language-server@1.0.0 postinstall script 'cd server && npm install && cd ../vscode-client && npm install && cd ..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bash-language-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd server && npm install && cd ../vscode-client && npm install && cd ..
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bash-language-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bash-language-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     bash-language-server\npm-debug.log

```

**Comment by mads-hartmann** [comment]
Yeah I think node-gyp (which is used to compile the tree-sitter parser on your machine) requires python. I'll see if I can package it in a different way, and if not, I'll update the README. Thanks :)

**Comment by mads-hartmann** [comment]
@maxbrunsfeld Any thoughts on what's the best way to distribute a node package that depends on a tree sitter parser? I don't have much experience shipping anything that isn't going onto a server somewhere ;)

**Comment by maxbrunsfeld** [comment]
Yeah I think the best way is to simply require python as a dependency, since this is the standard requirement for any native node module. I’m open to other ideas though.
