### ISSUE TITLE
Travis CI build is failing

### ISSUE THREAD

**Issue by rcjsuen** [mads-hartmann/bash-language-server#20]
Looks like the build [failed](https://travis-ci.org/mads-hartmann/bash-language-server/builds/363426716).
```
$ npm run check:bail

> @ check:bail /home/travis/build/mads-hartmann/bash-language-server
> npm run lint:bail && npm run test

> @ lint:bail /home/travis/build/mads-hartmann/bash-language-server
> tslint --project vscode-client && tslint --project server

> @ test /home/travis/build/mads-hartmann/bash-language-server
> jest --runInBand --forceExit

 FAIL  server/src/__tests__/analyzer.test.ts
  ● Test suite failed to run

    Cannot find module 'source-map-support' from 'install.js'
      
      at Resolver.resolveModule (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/ts-jest/dist/install.js:3:24)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.156s
Ran all test suites.
```

**Comment by mads-hartmann** [comment]
@skovhus Would you mind taking a look?

**Comment by skovhus** [comment]
@rcjsuen thanks for reporting this. Solved by switching to yarn.

**Comment by mads-hartmann** [comment]
Thanks @skovhus!
