### ISSUE TITLE
/usr/local/lib/node_modules/bash-language-server/node_modules/vscode-languageserver/lib/main.js:405     showErrorMessage(message, ...actions) {

### ISSUE THREAD

**Issue by bigxu** [mads-hartmann/bash-language-server#92]
➜  sharein git:(master) ✗ cat /etc/issue
Ubuntu 16.04.5 LTS \n \l

➜  sharein git:(master) ✗ bash-language-server -v
/usr/local/lib/node_modules/bash-language-server/node_modules/vscode-languageserver/lib/main.js:405
    showErrorMessage(message, ...actions) {
                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bash-language-server/out/index.js:3:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
➜  sharein git:(master) ✗

**Comment by aparks5** [comment]
I hit this exact error message today trying to start the language server from 16.04.

**Comment by skovhus** [comment]
Can you do a `node -v`?

**Comment by skovhus** [comment]
@bigxu @aparks5

Can you send us your node version (`node -v`)?

**Comment by aparks5** [comment]
Skovhus, I will get back to you Monday when I'm at my work machine with this, apologies for the lapse in response

**Comment by aparks5** [comment]
@skovhus managed to find some time to ssh in:
```
:~$ npm -v
3.5.2
:~$ node -v
v4.2.6
```

**Comment by skovhus** [comment]
We have just released a new version of `bash-language-server` (1.6.0) that:
- supports node > 8 (including 12)
- should remove all installation issues caused by node-gyp and native bindings

To upgrade run:
```
npm i -g bash-language-server
```

Let us know if this works for you. Thanks :)
