### ISSUE TITLE
Install error Failed at the tree-sitter@0.13.23 install script

### ISSUE THREAD

**Issue by doronbehar** [mads-hartmann/bash-language-server#93]
I'm getting an error when trying to install as `root` with `npm install -g bash-language-server`, here is the log from `/root/.npm/_logs/*.log` (after the successful dependencies installations):

```
4873 silly install tree-sitter@0.13.23
4874 info lifecycle tree-sitter@0.13.23~install: tree-sitter@0.13.23
4875 verbose lifecycle tree-sitter@0.13.23~install: unsafe-perm in lifecycle false
4876 verbose lifecycle tree-sitter@0.13.23~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/bash-language-server/node_modules/tree-sitter/node_modules/.bin:/usr/lib/node_modules/bash-language-server/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
4877 verbose lifecycle tree-sitter@0.13.23~install: CWD: /usr/lib/node_modules/bash-language-server/node_modules/tree-sitter
4878 silly lifecycle tree-sitter@0.13.23~install: Args: [ '-c', 'prebuild-install || node-gyp rebuild' ]
4879 silly lifecycle tree-sitter@0.13.23~install: Returned: code: 1  signal: null
4880 info lifecycle tree-sitter@0.13.23~install: Failed to exec install script
4881 timing action:install Completed in 418ms
4882 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
4883 timing stage:rollbackFailedOptional Completed in 267ms
4884 timing stage:runTopLevelLifecycles Completed in 50001ms
4885 verbose stack Error: tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
4885 verbose stack Exit status 1
4885 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
4885 verbose stack     at EventEmitter.emit (events.js:182:13)
4885 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4885 verbose stack     at ChildProcess.emit (events.js:182:13)
4885 verbose stack     at maybeClose (internal/child_process.js:978:16)
4885 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
4886 verbose pkgid tree-sitter@0.13.23
4887 verbose cwd /root
4888 verbose Linux 4.19.2-arch1-1-ARCH
4889 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bash-language-server"
4890 verbose node v11.2.0
4891 verbose npm  v6.4.1
4892 error code ELIFECYCLE
4893 error errno 1
4894 error tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
4894 error Exit status 1
4895 error Failed at the tree-sitter@0.13.23 install script.
4895 error This is probably not a problem with npm. There is likely additional logging output above.
4896 verbose exit [ 1, true ]
```

I've encountered a similar issue here: https://github.com/banacorn/language-agda/issues/15 but it happened on a Windows machine and I use Arch Linux.

Any ideas? Thanks.

**Comment by JulioJu** [comment]
Hi @doronbehar 
It seems that `bash-language-server` isn't compatible with `nodejs-lts-carbon` version 8.13.0. Install nodejs version 11.3.0 (`sudo pacman -S nodejs`) and all seems work when you use `bash-language-server start`. You could also install `bash-language-server` from community repo (`sudo pacman -S bash-language-server`). I am going to write a comment at https://www.archlinux.org/packages/community/x86_64/bash-language-server/ and post an issue at https://github.com/tree-sitter/tree-sitter/issues

@mads-hartmann could you add in your package.json 
`{ "engines" : { "node" : ">=11.3.0" } }`  (or other relevant version) and type command `npm config set engine-strict true` (see https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json).

Thanks in advance ! ;-)

**Comment by doronbehar** [comment]
Thanks.

**Comment by doronbehar** [comment]
@JulioJu , I've made my last comment from my phone without checking my node version. I've just reached my PC and my node's version and it is `11.3.0` - installed with `pacman -S nodejs`. It's not `nodejs-lts-carbon`. I'm using now the community provided package so it's this bug is not a big deal for me but I thought you should still know.

**Comment by octoquad** [comment]
I've also hit this problem with Node v8.14.0, v10.14.1 and v11.4.0 on Ubuntu 18.04. Let me know if you need any additional information.

**Comment by siddjain** [comment]
is there any solution for this problem? is there a different bash ide for vs code?

**Comment by siddjain** [comment]
I am using a mac

WITSC02X6385JGH:mads-hartmann.bash-ide-vscode-1.3.3 sjain68$ uname -a

Darwin WITSC02X6385JGH 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64

I got same error as beginning of this thread when I tried to install this package about 2 months ago. But today I did not get any error. I did not install with the -g flag though. I now see an error message in VS Code that says:
Can't find bash-language-server on your PATH. Please install it using "npm i -g bash-language-server".

How can I fix this? I did install bash-language-server under ~/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.3.3. below is complete output of installation.

WITSC02X6385JGH:~ sjain68$ cd ~/.vscode/extensions
WITSC02X6385JGH:extensions sjain68$ ls
dbaeumer.vscode-eslint-1.7.2  ms-vsts.team-1.144.1
donjayamanne.githistory-0.4.4  nobuhito.printcode-3.0.0
eg2.tslint-1.0.42   peterjausovec.vscode-docker-0.4.0
mads-hartmann.bash-ide-vscode-1.3.3 rogalmic.bash-debug-0.3.3
ms-vscode.go-0.8.0
WITSC02X6385JGH:extensions sjain68$ cd mads-hartmann.bash-ide-vscode-1.3.3/
WITSC02X6385JGH:mads-hartmann.bash-ide-vscode-1.3.3 sjain68$ npm install bash-language-server
npm WARN deprecated boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> tree-sitter@0.13.23 install /Users/sjain68/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.3.3/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild


> tree-sitter-bash@0.13.7 install /Users/sjain68/.vscode/extensions/mads-hartmann.bash-ide-vscode-1.3.3/node_modules/tree-sitter-bash
> prebuild-install || node-gyp rebuild

npm notice created a lockfile as package-lock.json. You should commit this file.
+ bash-language-server@1.5.5
added 145 packages from 210 contributors, removed 14 packages, updated 281 packages and audited 1379 packages in 15.744s
found 9 vulnerabilities (8 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
WITSC02X6385JGH:mads-hartmann.bash-ide-vscode-1.3.3 sjain68$
WITSC02X6385JGH:mads-hartmann.bash-ide-vscode-1.3.3 sjain68$ npm audit fix
+ vscode@1.1.26
added 44 packages from 71 contributors, removed 123 packages, updated 25 packages and moved 4 packages in 4.23s
fixed 9 of 9 vulnerabilities in 1379 scanned packages


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │       New minor version of npm available! 6.4.1 → 6.5.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.5.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯


WITSC02X6385JGH:mads-hartmann.bash-ide-vscode-1.3.3 sjain68$ ls -al node_modules/bash-language-server/

total 136

drwxr-xr-x   12 sjain68  staff    384 Jan  7 08:17 .

drwxr-xr-x  296 sjain68  staff   9472 Jan  7 08:18 ..

-rw-r--r--    1 sjain68  staff   2276 Oct 26  1985 CHANGELOG.md

-rw-r--r--    1 sjain68  staff    428 Oct 26  1985 README.md

drwxr-xr-x    3 sjain68  staff     96 Jan  7 08:17 bin

drwxr-xr-x   15 sjain68  staff    480 Jan  7 08:17 out

-rw-r--r--    1 sjain68  staff   1960 Jan  7 08:17 package.json

-rw-r--r--    1 sjain68  staff      0 Oct 26  1985 setupJest.ts

drwxr-xr-x   10 sjain68  staff    320 Jan  7 08:17 src

-rw-r--r--    1 sjain68  staff    161 Oct 26  1985 tsconfig.json

-rw-r--r--    1 sjain68  staff     39 Oct 26  1985 tslint.json

-rw-r--r--    1 sjain68  staff  46888 Oct 26  1985 yarn.lock


________________________________

**Comment by octoquad** [comment]
Node: v11.6.0 (tried with past versions also, see above)
NPM: 6.5.0
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

```
$ sudo npm install -g bash-language-server                                                                                                                                                          
/usr/bin/bash-language-server -> /usr/lib/node_modules/bash-language-server/bin/main.js

> tree-sitter@0.13.23 install /usr/lib/node_modules/bash-language-server/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/home/bruce/.npm'
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/bash-language-server/node_modules/tree-sitter/build'
gyp ERR! System Linux 4.15.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/bash-language-server/node_modules/tree-sitter
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter@0.13.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-01-08T14_14_14_626Z-debug.log
```

**Comment by sbrl** [comment]
I think I have this problem too. Output:

```
$ sudo npm i -g bash-language-server
/usr/local/bin/bash-language-server -> /usr/local/lib/node_modules/bash-language-server/bin/main.js

> tree-sitter@0.13.23 install /usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/home/sbrl/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/sbrl/.node-gyp/11.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter/.node-gyp'
gyp ERR! System Linux 4.18.0-13-generic
gyp ERR! command "/usr/local/lib/node-v11.6.0-linux-x64/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter@0.13.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sbrl/.npm/_logs/2019-01-14T00_34_36_463Z-debug.log
```

 - Node.JS v11.6.0
 - npm v6.5.0

I think this project needs some love and attention.

**Comment by skovhus** [comment]
@sbrl those issue are not related. What you see is a permission issue with your npm and node installation. 

There are several guides online on how to solve that. Official documentation might be a good start: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by sbrl** [comment]
@skovhus: I see. However, I have installed packages globally successfully before, and not encountered any issues. Examples include `sloc`, `wscat`, `npm-remote-ls`, and `npm-check`.

**Comment by siddjain** [comment]
adding this link explaining how to install and use bash-language-server in non-global mode
https://github.com/mads-hartmann/bash-language-server/issues/97

**Comment by skovhus** [comment]
@doronbehar closed due to inactivity. Hope you found a solution, else please create a new issue.

**Comment by doronbehar** [comment]
The error is still there, I've also tried also manually creating `/root/.node-gyp/11.12.0` and it removed some of the errors but these still persist:

```
/usr/bin/bash-language-server -> /usr/lib/node_modules/bash-language-server/bin/main.js

> tree-sitter@0.13.23 install /usr/lib/node_modules/bash-language-server/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EPERM: operation not permitted, utime '/root/.node-gyp/11.12.0'
gyp ERR! System Linux 5.0.3-arch1-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/bash-language-server/node_modules/tree-sitter
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.13.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-24T07_05_13_482Z-debug.log
```

This is kind of insane that root doens't have access to these directories and with `ls -ld .npm` I see that root does have access to it. Also adding `--unsage-perm` didn't help either.

**Comment by doronbehar** [comment]
Update: This fixed the issue here on Arch Linux along with `--unsafe-perm`: https://wiki.archlinux.org/index.php/Node.js#node-gyp_python_errors

Well done Arch Wiki, you did it again. Cheers.

**Comment by sbrl** [comment]
Ah, excellent! Glad you found a solution, @doronbehar. In that case, perhaps we should open a new issue to get it upgraded to Python 3?

**Comment by skovhus** [comment]
Note that python is not used as a direct dependency here, but `node-gyp` is the issue here. 

A section in the README with details on resolving install issues would be very appreciated. 

Related: https://github.com/nodejs/node-gyp/blob/master/README.md#configuring-python-dependency

**Comment by gmolau** [comment]
Can this be opened again? I've tried all suggestions in this thread, it still doesn't work.

**Comment by doronbehar** [comment]
Are you sure you have set `python=/usr/bin/python2` (or wherever python2 is installed on your system) in your npmrc?

**Comment by gmolau** [comment]
Yes, it's using the macOS system python. This is the output I'm getting:

```
▶ npm i -g bash-language-server
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
/usr/local/bin/bash-language-server -> /usr/local/lib/node_modules/bash-language-server/bin/main.js

> tree-sitter@0.13.23 install /usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.9.1 runtime=node arch=x64 libc= platform=darwin)
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/get_changed_ranges.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/language.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/lexer.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/node.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/stack.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/parser.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/subtree.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/tree.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/tree_cursor.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/src/runtime/utf16.o
  CC(target) Release/obj.target/runtime/vendor/tree-sitter/externals/utf8proc/utf8proc.o
  LIBTOOL-STATIC Release/runtime.a
  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
  CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/conversions.o
../src/conversions.cc:32:12: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  exports->Set(Nan::New("pointTransferArray").ToLocalChecked(), Uint32Array::New(js_point_transfer_buffer, 0, 2));
           ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:42:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  result->Set(Nan::New(start_position_key), PointToJS(range.start_point));
          ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:43:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  result->Set(Nan::New(start_index_key), ByteCountToJS(range.start_byte));
          ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:44:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  result->Set(Nan::New(end_position_key), PointToJS(range.end_point));
          ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:45:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  result->Set(Nan::New(end_index_key), ByteCountToJS(range.end_byte));
          ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:68:3: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  INIT(start_point, start_position_key, PointFromJS);
  ^
../src/conversions.cc:60:33: note: expanded from macro 'INIT'
    auto field = Type(js_range->Get(Nan::New(key))); \
                                ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:69:3: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  INIT(end_point, end_position_key, PointFromJS);
  ^
../src/conversions.cc:60:33: note: expanded from macro 'INIT'
    auto field = Type(js_range->Get(Nan::New(key))); \
                                ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:70:3: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  INIT(start_byte, start_index_key, ByteCountFromJS);
  ^
../src/conversions.cc:60:33: note: expanded from macro 'INIT'
    auto field = Type(js_range->Get(Nan::New(key))); \
                                ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:71:3: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  INIT(end_byte, end_index_key, ByteCountFromJS);
  ^
../src/conversions.cc:60:33: note: expanded from macro 'INIT'
    auto field = Type(js_range->Get(Nan::New(key))); \
                                ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:80:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  result->Set(Nan::New(row_key), Nan::New<Number>(point.row));
          ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:81:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  result->Set(Nan::New(column_key), ByteCountToJS(point.column));
          ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3371:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:92:35: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  Local<Value> js_row = js_point->Get(Nan::New(row_key));
                                  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:98:38: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
  Local<Value> js_column = js_point->Get(Nan::New(column_key));
                                     ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:3425:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/conversions.cc:105:41: error: too few arguments to function call, single argument 'context' was not specified
  if (std::isfinite(js_row->NumberValue())) {
                    ~~~~~~~~~~~~~~~~~~~ ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2577:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:106:52: error: too few arguments to function call, single argument 'context' was not specified
    row = static_cast<uint32_t>(js_row->Int32Value());
                                ~~~~~~~~~~~~~~~~~~ ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2582:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:111:44: error: too few arguments to function call, single argument 'context' was not specified
  if (std::isfinite(js_column->NumberValue())) {
                    ~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2577:3: note: 'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:112:58: error: too few arguments to function call, single argument 'context' was not specified
    column = static_cast<uint32_t>(js_column->Int32Value()) * BYTES_PER_CHARACTER;
                                   ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2582:3: note: 'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/conversions.cc:130:47: error: too few arguments to function call, single argument 'context' was not specified
  return Nan::Just<uint32_t>(arg->Uint32Value() * BYTES_PER_CHARACTER);
                             ~~~~~~~~~~~~~~~~ ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2580:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/g.molau/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
13 warnings and 5 errors generated.
make: *** [Release/obj.target/tree_sitter_runtime_binding/src/conversions.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.9.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.13.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/g.molau/.npm/_logs/2019-09-21T11_50_29_982Z-debug.log
```

**Comment by skovhus** [comment]
We are unfortunately not compatible with node 12. Please try downgrading to node 10.

**Comment by gmolau** [comment]
Ok thanks, it works with v10. Maybe this could be mentioned in the README, it would have saved me some trial and error.

**Comment by sbrl** [comment]
Indeed. Advertising this fact in the README would be a very good idea I think. I've got the latest current version (v12) installed, so I guess that means I can't use bash-language-server then :-/

**Comment by skovhus** [comment]
We have just released a new version of `bash-language-server` (1.6.0) that:
- supports node > 8 (including 12)
- should remove all installation issues caused by node-gyp and native bindings

To upgrade run:
```
npm i -g bash-language-server
```

Let us know if this works for you. Thanks :)

**Comment by gmolau** [comment]
@skovhus works like a charm, thank you!

**Comment by sbrl** [comment]
Note to Linux users: Don't forget `sudo`:

````bash
sudo npm install --global bash-language-server
````

**Comment by doronbehar** [comment]
@skovhus I thought bash-language-server depends on node-tree-sitter which doesn't work with node 12 (https://github.com/tree-sitter/node-tree-sitter/issues/46).

**Comment by skovhus** [comment]
> @skovhus I thought bash-language-server depends on node-tree-sitter which doesn't work with node 12 (tree-sitter/node-tree-sitter#46).

I did until recently. See https://github.com/mads-hartmann/bash-language-server/issues/93#issuecomment-534408367 and #147
