### ISSUE TITLE
issue with tree-sitter

### ISSUE THREAD

**Issue by JulioJu** [mads-hartmann/bash-language-server#95]
Hi,

When I try to start `bash-language-server` in command line, I have the following error:

```
/usr/lib/bash-language-server/node_modules/tree-sitter/index.js:8
    throw e;
    ^

Error: The module '/usr/lib/bash-language-server/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/bash-language-server/node_modules/tree-sitter/index.js:3:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

As they advise, in `/usr/lib/bash-language-server/node_modules/tree-sitter` I've executed `npm install` and `npm rebuild` without more result.

I've tested with node js lts version `8.13.0`.

Thanks in advance :-)

**Comment by JulioJu** [comment]
Probably, it's the same issue that https://github.com/mads-hartmann/bash-language-server/issues/93.

I'm also with Arch Linux.

**Comment by JulioJu** [comment]
See https://github.com/mads-hartmann/bash-language-server/issues/93#issuecomment-442455951
