### ISSUE TITLE
Bash IDE 1.3.3 crashes attempting open link file

### ISSUE THREAD

**Issue by JulianLian** [mads-hartmann/bash-language-server#98]
VSCode 1.30.2
Ubuntu 18.04
Bash IDE version 1.3.3

```
Analyzing file:///home/Julian/Code/release/layout/pkg/BUILDROOT/usr/lib/systemd/system-sleep/ctxvda.sh
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/Julian/Code/release/layout/pkg/BUILDROOT/usr/lib/systemd/system-sleep/ctxvda.sh'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at paths.forEach.p (/usr/local/lib/node_modules/bash-language-server/out/analyser.js:64:91)
    at Array.forEach (<anonymous>)
    at glob (/usr/local/lib/node_modules/bash-language-server/out/analyser.js:60:27)
    at f (/usr/local/lib/node_modules/bash-language-server/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/usr/local/lib/node_modules/bash-language-server/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/usr/local/lib/node_modules/bash-language-server/node_modules/glob/glob.js:197:8)
[Error - 10:33:53 AM] Connection to server got closed. Server will not be restarted.
```
Where ctxvda.sh symlinks to another file.

**Comment by JulianLian** [comment]
Sorry. I've make a mistake. The error was caused by that the target file doesn't exist.
